name: dotnet-build

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build .NET
    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest] #,windows-latest]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: ğŸ“„ Checkout
      uses: actions/checkout@v4

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1.67.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: false
      
    - name: ğŸ› ï¸ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: ğŸ› ï¸ Restore dependencies
      run: dotnet restore
    - name: ğŸš€ Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: ğŸ“¦ Pack NuGet package
      run: dotnet pack -p VersionPrefix=${{github.event.release.tag_name}} -p ReleaseNotes="${{github.event.release.body}}"

    - name: ğŸ’¾ Archive package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: /home/runner/work/cuddly-winner/cuddly-winner/src/GithubNugetWorkflowPoc/bin/Release/GithubNugetWorkflowPoc.*.nupkg

    - name: ğŸ’¾ Archive symbols package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: /home/runner/work/cuddly-winner/cuddly-winner/src/GithubNugetWorkflowPoc/bin/Release/GithubNugetWorkflowPoc.*.snupkg

    - name: ğŸ› ï¸ Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'

    - name: ğŸŒ Push NuGet package live
      run: nuget push/home/runner/work/cuddly-winner/cuddly-winner/src/GithubNugetWorkflowPoc/bin/Release/GithubNugetWorkflowPoc.*.nupkg -src https://api.nuget.org/v3/index.json
      shell: powershell

    - name: ğŸŒ Push NuGet symbol package live
      run: nuget push /home/runner/work/cuddly-winner/cuddly-winner/src/GithubNugetWorkflowPoc/bin/Release/GithubNugetWorkflowPoc.*.snupkg -src https://api.nuget.org/v3/index.json
      shell: powershell